# Generated by Django 2.2.12 on 2021-01-11 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_management', '0012_auto_20201229_1225'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='closed_date',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='description',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='estimated_date',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='phase',
            field=models.IntegerField(choices=[(1, 'Project Initiation'), (2, 'Project Planning'), (3, 'Project Execution'), (2, 'Project Monitoring and Control'), (3, 'Project Closed')], default=1),
        ),
    ]
