# Generated by Django 2.2.12 on 2021-01-11 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_management', '0013_auto_20210111_1310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='phase',
            field=models.CharField(choices=[('PI', 'Project Initiation'), ('PP', 'Project Planning'), ('PE', 'Project Execution'), ('PMC', 'Project Monitoring and Control'), ('PC', 'Project Closed')], default='PI', max_length=3),
        ),
    ]
